language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

notifications:
  slack:
    rooms:
      - shopclientapp:EBh1k4fcosP8EYhbD1R0S2qm#android
  email: false
  
branches:
  only:
    - master
    - develop
    - feature/implement_magento_api
    - /^feature\/magento.*$/

script:
  - ./gradlew build jacocoTestReport connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)

